#!/bin/bash
clear

export CUDA_VISIBLE_DEVICES=5,6

./bin/C2C spine_muscle_adipose_tissue \
    -i "/home/qhe2/Documents/Datasets/Pancreatic/" \
    -o "outputs/" \
    --spine_model ts_spine_full \
    --muscle_fat_model voxtell_v1.1

unset CUDA_VISIBLE_DEVICES
